In [2]:
import pandas as pd
import requests
import git
from datetime import date

           
def cambioFecha(texto):
    aux = str(texto)
    
    traductor ={
        "Jan" : 1,
        "Feb" : 2,
        "Mar" : 3,
        "Apr" : 4
    }
    try:
        mes = traductor[aux[:3]]
    except:
        mes = 12
    #datetime.date(2019, 12, 4)
    #dia = int(aux[4:7])
    try:
        dia = int(aux[4:7])
    except:
        return None
    salida = datetime.date(2020,mes,dia)
    return salida.strftime("%d-%m-%Y")
    #return aux[:3]

url  = 'https://www.worldometers.info/coronavirus/'
response = requests.get(url)
#print(response.content)
data = pd.read_html(response.content)
data_hoy = data[0]     #.to_csv("worldometers.csv", index=False)
#data_ayer = data[1]     #.to_csv("worldometersAYER.csv", index=False)

#data_hoy["Primer caso"] = data_hoy["Reported1st case"].apply(cambioFecha)
#data_ayer["Primer caso"] = data_ayer["Reported1st case"].apply(cambioFecha)

data_aux = pd.read_csv("Historico/worldometers.csv")

for i in data_aux.columns[1:10]:
    #print(i)
    del data_aux[i]
#del data_aux["TotalCases"]
#del data_aux["NewCases"]
#del data_aux["TotalDeaths"]
#del data_aux["NewDeaths"]
#del data_aux["TotalRecovered"]
#del data_aux["ActiveCases"]
#del data_aux["Serious,Critical"]
#del data_aux["Tot Cases/1M pop"]
#del data_aux['Deaths/1M pop']

merged_left = pd.merge(left=data_hoy, right=data_aux, how='left', left_on='Country,Other', right_on='Country,Other')
merged_left.to_csv("worldometers.csv", index=False)

#data_hoy.to_csv("worldometers.csv", index=False)
#data_ayer.to_csv("worldometersAYER.csv", index=False)


url  = 'https://www.worldometers.info/world-population/population-by-country/'
response = requests.get(url)
#print(response.content)
data = pd.read_html(response.content)[0]

data.to_csv("Poblacion/worldometersPoblacion.csv", index=False)



repoLocal = git.Repo('C:/Users/limc_/Documents/GitHub/Datos' )
print(repoLocal.git.status())
#repoLocal.git.add(".")
repoLocal.git.add(".")
try:
    repoLocal.git.commit(m='Update automatico via python')
except:
    pass

origin = repoLocal.remote(name='origin')
origin.push()

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ecdc.europa/SacarDatos.ipynb
	modified:   ourworldindata.org/SacarDatos.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [34]:
import pandas as pd
import requests
import git
from datetime import date

url  = 'https://www.worldometers.info/world-population/population-by-country/'
response = requests.get(url)
#print(response.content)
data = pd.read_html(response.content)[0]
data

,#,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,1,China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,2,India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,3,United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,4,Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,5,Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
231,232,Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
232,233,Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
234,235,Holy See,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [33]:
data[0].head()

,#,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,1,China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,2,India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,3,United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,4,Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,5,Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %

In [25]:
texto = "hola"
texto[2:4]

'la'

In [24]:
int("04")

4

In [38]:
traductor ={
        "Jan" : 1,
        "Feb" : 2,
        "Mar" : 3
    }

In [32]:
traductor["Jan"]

1

In [30]:
#data_hoy
data_aux = pd.read_csv("Historico/worldometers.csv")

for i in data_aux.columns[1:10]:
    print(i)
    del data_aux[i]
#del data_aux["TotalCases"]
#del data_aux["NewCases"]
#del data_aux["TotalDeaths"]
#del data_aux["NewDeaths"]
#del data_aux["TotalRecovered"]
#del data_aux["ActiveCases"]
#del data_aux["Serious,Critical"]
#del data_aux["Tot Cases/1M pop"]
#del data_aux['Deaths/1M pop']

merged_left = pd.merge(left=data_hoy, right=data_aux, how='left', left_on='Country,Other', right_on='Country,Other')
merged_left.to_csv("worldometers.csv", index=False)

#data_aux.columns

TotalCases
NewCases
TotalDeaths
NewDeaths
TotalRecovered
ActiveCases
Serious,Critical
Tot Cases/1M pop
Deaths/1M pop