In [34]:
import pandas as pd
#from datetime import datetime, timedelta
import datetime
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/input/Covid-19.csv Principal
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto1/Covid-19.csv #Casos totales por comuna incremental:
# Casos totales por comuna
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/2020-03-30-CasosConfirmados.csv
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/2020-04-01-CasosConfirmados.csv
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/2020-04-03-CasosConfirmados.csv
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/2020-04-06-CasosConfirmados.csv
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/2020-04-08-CasosConfirmados.csv
#Casos totales por región incremental:
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto3/CasosTotalesCumulativo.csv
#Casos totales por región 
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto4/2020-03-03-CasosConfirmados-totalRegional.csv
#...
#https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto4/2020-04-09-CasosConfirmados-totalRegional.csv
#Casos totales recuperados
# https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto5/recuperados.csv

def realizarColumna(data, largo):
    lista = list(data.iterrows())
    data_aux = data
    try:
        del data_aux["Tasa"]
    except:
        pass
    data_aux.columns
    salida = []
    for i in lista:
        #print(i[1])
        try:
            aux = {"Region":i[1]["Region"],"Comuna":i[1]["Comuna"],"Poblacion":i[1]["Poblacion"],"Tasa":i[1]["Tasa"]}
        except:
            aux = {"Region":i[1]["Region"],"Comuna":i[1]["Comuna"],"Poblacion":i[1]["Poblacion"]}
        for j in data_aux.columns[largo:]:
            entrada = aux.copy()
            #entrada[j] = 
            entrada["Fecha"] = j
            entrada["Cantidad"] = i[1][j]
            salida.append(entrada.copy())

    return pd.DataFrame(salida) 

def realizarColumnaParticular(data, key):
    lista = list(data.iterrows())
    data_aux = data
    data_aux.columns
    salida = []
    for i in lista[key:]:
        #print(i[1])
        aux = {key:i[1][key]}
        for j in data_aux.columns[1:]:
            entrada = aux.copy()
            #entrada[j] = 
            entrada["fecha"] = j
            entrada["Recuperado"] = i[1][j]
            salida.append(entrada.copy())

    return pd.DataFrame(salida)



def minsal():
    url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/input/Covid-19.csv"
    try:        
        data = realizarColumna(pd.read_csv(url),3)
        data.to_csv("Principal.csv", index=False)
    except:
        pass

    url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto1/Covid-19.csv"
    data = realizarColumna(pd.read_csv(url),3)
    data.to_csv("Producto1.csv", index=False)

    salida = []
    inicio = datetime.datetime(2020,3,30)
    fin    = datetime.datetime.now()
    url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/"  #2020-03-30-CasosConfirmados.csv
    lista_fechas = [inicio + datetime.timedelta(days=d) for d in range((fin - inicio).days + 1)] 
    for i in lista_fechas:
        try:
            data = pd.read_csv(url + i.strftime("%Y-%m-%d-CasosConfirmados.csv"))
            data["Fecha"] = i.strftime("%d-%m-%Y")
            salida.append(data)
        except:
            pass

    data =pd.concat(salida)
    data.to_csv("Producto2.csv", index=False)

    url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto3/CasosTotalesCumulativo.csv"
    data = realizarColumnaParticular(pd.read_csv(url),"Region")
    data.to_csv("Producto3.csv", index=False)

    salida = []
    inicio = datetime.datetime(2020,3,3)
    fin    = datetime.datetime.now()

    url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto4/"  #2020-03-03-CasosConfirmados-totalRegional.csv
    lista_fechas = [inicio + datetime.timedelta(days=d) for d in range((fin - inicio).days + 1)] 
    for i in lista_fechas:
        try:
            data = pd.read_csv(url + i.strftime("%Y-%m-%d-CasosConfirmados-totalRegional.csv"))
            data["Fecha"] = i.strftime("%d-%m-%Y")
            salida.append(data)
        except:
            pass
    data =pd.concat(salida)
    data.to_csv("Producto4.csv", index=False)

    url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto5/recuperados.csv"
    data = realizarColumnaParticular(pd.read_csv(url),"Fecha")
    #data["Estado"] = data["Fecha"]
    del data["Fecha"]

    data.to_csv("Producto5.csv", index=False)
    return

In [37]:
url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/"  #2020-03-30-CasosConfirmados.csv

(1730, 5)

In [65]:
#url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto5/recuperados.csv"
#data = realizarColumnaParticular(pd.read_csv(url),"Fecha")
#data.to_csv("Producto5.csv", index=False)
data = pd.read_csv("Producto3.csv")
data

                 Region       fecha  Recuperado
0    Arica y Parinacota  2020-03-03           0
1    Arica y Parinacota  2020-03-04           0
2    Arica y Parinacota  2020-03-05           0
3    Arica y Parinacota  2020-03-06           0
4    Arica y Parinacota  2020-03-07           0
..                  ...         ...         ...
658               Total  2020-04-06        4815
659               Total  2020-04-07        5116
660               Total  2020-04-08        5546
661               Total  2020-04-09        5972
662               Total  2020-04-10        6501

[663 rows x 3 columns]

In [35]:
minsal()

TypeError: slice indices must be integers or None or have an __index__ method

In [20]:
data_final = pd.DataFrame(salida)
data_final

                         Region            Comuna  Poblacion Fecha
0            Arica y Parinacota             Arica     247552     6
1            Arica y Parinacota             Arica     247552     6
2            Arica y Parinacota             Arica     247552    12
3            Arica y Parinacota             Arica     247552    41
4            Arica y Parinacota             Arica     247552    63
...                         ...               ...        ...   ...
1725  Magallanes y la Antartica  Torres del Paine       1021     -
1726  Magallanes y la Antartica  Torres del Paine       1021     -
1727  Magallanes y la Antartica  Torres del Paine       1021     -
1728  Magallanes y la Antartica  Torres del Paine       1021     -
1729  Magallanes y la Antartica  Torres del Paine       1021     -

[1730 rows x 4 columns]

In [33]:
import pandas as pd
pd.read_csv("Producto1.csv")

,Region,Comuna,Poblacion,Tasa,Fecha,Cantidad
0,Arica y Parinacota,Arica,247552.0,50.1,Codigo comuna,15101
1,Arica y Parinacota,Arica,247552.0,50.1,Poblacion,247552.0
2,Arica y Parinacota,Arica,247552.0,50.1,2020-03-30,6
3,Arica y Parinacota,Arica,247552.0,50.1,2020-04-01,6
4,Arica y Parinacota,Arica,247552.0,50.1,2020-04-03,12
...,...,...,...,...,...,...
3455,Magallanes,Torres del Paine,1021.0,0.0,2020-04-06,-
3456,Magallanes,Torres del Paine,1021.0,0.0,2020-04-08,-
3457,Magallanes,Torres del Paine,1021.0,0.0,2020-04-10,-
3458,Magallanes,Torres del Paine,1021.0,0.0,2020-04-13,-
3459,Magallanes,Torres del Paine,1021.0,0.0,2020-04-15,-

In [47]:
url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto1/Covid-19.csv"
data = pd.read_csv(url)

lista = list(data.iterrows())
data_aux = data
data_aux.columns
salida = []
for i in lista:
    aux = {key:i[1][key]}
    for j in data_aux.columns[1:]:
        entrada = aux.copy()
        #entrada[j] = 
        entrada["fecha"] = j
        entrada["Recuperado"] = i[1][j]
        salida.append(entrada.copy())
pd.DataFrame(salida)

NameError: name 'key' is not defined

In [67]:
import pandas as pd
#from datetime import datetime, timedelta
import datetime
#url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto1/Covid-19.csv"
#data = pd.read_csv(url)
def TransponerFecha(data,key, borrarColumnas = []):
    for i in borrarColumnas:
        try:
            del data[i]
        except:
            pass
    lista = list(data.iterrows())
    data_aux = data
    salida = []
    for i in lista:
        aux = {"aux": ""}
        for j in data_aux.columns[:key]:
            aux[j] = i[1][j]
        for j in data_aux.columns[key:]:
            aux["fecha"] = j
            aux["Cantidad"] = i[1][j]
            salida.append(aux.copy())
    data_salida = pd.DataFrame(salida)
    del data_salida["aux"]
    return data_salida

def minsal():
    url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto1/Covid-19.csv"
    data = TransponerFecha(pd.read_csv(url),4, ["Tasa"])
    data.to_csv("Producto1.csv", index=False)

    salida = []
    inicio = datetime.datetime(2020,3,30)
    fin    = datetime.datetime.now()
    url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto2/"  #2020-03-30-CasosConfirmados.csv
    lista_fechas = [inicio + datetime.timedelta(days=d) for d in range((fin - inicio).days + 1)] 
    for i in lista_fechas:
        try:
            data = pd.read_csv(url + i.strftime("%Y-%m-%d-CasosConfirmados.csv"))
            data["Fecha"] = i.strftime("%d-%m-%Y")
            salida.append(data)
        except:
            pass
    data =pd.concat(salida)
    data.to_csv("Producto2.csv", index=False)

    url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto3/CasosTotalesCumulativo.csv"
    data = TransponerFecha(pd.read_csv(url),1)
    data.to_csv("Producto3.csv", index=False)

    salida = []
    inicio = datetime.datetime(2020,3,3)
    fin    = datetime.datetime.now()
    url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto4/"  #2020-03-03-CasosConfirmados-totalRegional.csv
    lista_fechas = [inicio + datetime.timedelta(days=d) for d in range((fin - inicio).days + 1)] 
    for i in lista_fechas:
        try:
            data = pd.read_csv(url + i.strftime("%Y-%m-%d-CasosConfirmados-totalRegional.csv"))
            data["Fecha"] = i.strftime("%d-%m-%Y")
            salida.append(data)
        except:
            pass
    data =pd.concat(salida)
    data.to_csv("Producto4.csv", index=False)

    url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto5/recuperados.csv"
    data = TransponerFecha(pd.read_csv(url),1)
    #data["Estado"] = data["Fecha"]
    data["Estado"] = data["Fecha"]
    del data["Fecha"]

    data.to_csv("Producto5.csv", index=False)
    return

minsal()

In [66]:
url = "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto5/recuperados.csv"
data = TransponerFecha(pd.read_csv(url),1)
data

          Fecha       fecha  Cantidad
0   Recuperados  2020-03-17         1
1   Recuperados  2020-03-18         3
2   Recuperados  2020-03-19         4
3   Recuperados  2020-03-20         5
4   Recuperados  2020-03-21         6
5   Recuperados  2020-03-22         8
6   Recuperados  2020-03-23        11
7   Recuperados  2020-03-24        17
8   Recuperados  2020-03-25        22
9   Recuperados  2020-03-26        33
10  Recuperados  2020-03-27        43
11  Recuperados  2020-03-28        61
12  Recuperados  2020-03-29        75
13  Recuperados  2020-03-30       156
14  Recuperados  2020-03-31       201
15  Recuperados  2020-04-01       234
16  Recuperados  2020-04-02       335
17  Recuperados  2020-04-03       427
18  Recuperados  2020-04-04       528
19  Recuperados  2020-04-05       617
20  Recuperados  2020-04-06       728
21  Recuperados  2020-04-07       898
22  Recuperados  2020-04-08      1115
23  Recuperados  2020-04-09      1274
24  Recuperados  2020-04-10      1571
25  Recuperados  2020-04-11      1864
26  Recuperados  2020-04-12      2059
27  Recuperados  2020-04-13      2367
28  Recuperados  2020-04-14      2646
29  Recuperados  2020-04-15      2937
30  Recuperados  2020-04-16      3299
31  Recuperados  2020-04-17      3621